import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { CompetitionsDashboardStats } from "@/lib/competitions/dashboard"

const number = new Intl.NumberFormat("fr-FR")
export function CompetitionsSummarySection({ stats }: { stats: CompetitionsDashboardStats }) {
  const total = stats.types.reduce((sum, item) => ({ total: sum.total + item.total, aVenir: sum.aVenir + item.aVenir, enCours: sum.enCours + item.enCours, terminees: sum.terminees + item.terminees, equipesNationales: sum.equipesNationales + item.equipesNationales }), { total: 0, aVenir: 0, enCours: 0, terminees: 0, equipesNationales: 0 })
  const cells = (item: typeof total) => <><TableCell className="text-right tabular-nums">{number.format(item.total)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.aVenir)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.enCours)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.terminees)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.equipesNationales)}</TableCell></>
  return <section aria-labelledby="competitions-title" className="space-y-4"><div className="space-y-2"><h2 id="competitions-title" className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.16em] text-primary/80 before:h-0.5 before:w-8 before:bg-primary/80">Compétitions</h2><p className="text-sm text-muted-foreground">Répartition par type, statut et équipes nationales concernées</p></div><div className="overflow-x-auto rounded-xl border border-border/70 bg-card/80 shadow-[0_10px_28px_rgba(7,25,54,.04)]"><Table><TableHeader><TableRow className="bg-secondary/80 hover:bg-secondary/80"><TableHead>Type de compétition</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">À venir</TableHead><TableHead className="text-right">En cours</TableHead><TableHead className="text-right">Terminées</TableHead><TableHead className="text-right">Équipes nationales</TableHead></TableRow></TableHeader><TableBody>{stats.types.map((item) => <TableRow key={item.key}><TableCell className="font-medium">{item.label}</TableCell>{cells(item)}</TableRow>)}{!stats.types.length && <TableRow><TableCell colSpan={6} className="h-24 text-center text-muted-foreground">Aucune compétition enregistrée.</TableCell></TableRow>}<TableRow className="border-t-2 bg-secondary/40 font-semibold hover:bg-secondary/40"><TableCell>Total</TableCell>{cells(total)}</TableRow></TableBody></Table></div></section>
}
