import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import type { NationalTeamsDashboardStats } from "@/lib/equipes-nationales/dashboard"

const number = new Intl.NumberFormat("fr-FR")
export function NationalTeamsSummarySection({ stats }: { stats: NationalTeamsDashboardStats }) {
  const total = { total: stats.totalTeams, active: stats.activeTeams, inactive: stats.inactiveTeams, members: stats.totalMembers }
  const cells = (item: typeof total) => <><TableCell className="text-right tabular-nums">{number.format(item.total)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.active)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.inactive)}</TableCell><TableCell className="text-right tabular-nums">{number.format(item.members)}</TableCell></>
  return <section className="space-y-4"><div className="space-y-2"><h2 className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.16em] text-primary/80 before:h-0.5 before:w-8 before:bg-primary/80">Équipes nationales</h2><p className="text-sm text-muted-foreground">Répartition des équipes et membres actifs distincts par sport</p></div><div className="overflow-x-auto rounded-xl border border-border/70 bg-card/80 shadow-[0_10px_28px_rgba(7,25,54,.04)]"><Table><TableHeader><TableRow className="bg-secondary/80 hover:bg-secondary/80"><TableHead>Sport</TableHead><TableHead className="text-right">Équipes</TableHead><TableHead className="text-right">Actives</TableHead><TableHead className="text-right">Inactives</TableHead><TableHead className="text-right">Membres actifs</TableHead></TableRow></TableHeader><TableBody>{stats.sports.map((item) => <TableRow key={item.key}><TableCell>{item.label}</TableCell>{cells(item)}</TableRow>)}{!stats.sports.length && <TableRow><TableCell colSpan={5} className="h-24 text-center text-muted-foreground">Aucune équipe nationale enregistrée.</TableCell></TableRow>}<TableRow className="border-t-2 bg-secondary/40 font-semibold"><TableCell>Total</TableCell>{cells(total)}</TableRow></TableBody></Table></div></section>
}
