const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const {chromium}=require('@playwright/test');const {webpack}=require('next/dist/compiled/webpack/webpack');
test('CNAC dashboard KPIs, partial outage, permissions, refresh and responsive layout',{timeout:120000},async()=>{
 const root=path.resolve(__dirname,'../..'),output=path.join(root,'.cache/cnac-dashboard-ui');await fs.mkdir(output,{recursive:true});
 await fs.writeFile(path.join(output,'loader.cjs'),`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=function(source){return ts.transpileModule(source,{fileName:this.resourcePath,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText}`);
 await fs.writeFile(path.join(output,'navigation.ts'),`export const useRouter=()=>({refresh(){window.refreshCount=(window.refreshCount||0)+1},push(){}});export const usePathname=()=>'/dashboard';export const useSearchParams=()=>new URLSearchParams();`);
 await fs.writeFile(path.join(output,'data.ts'),`import{actorMetrics,territorialMetrics,aggregateCnacMetrics}from'@/lib/dashboard/cnac-metrics';export const canAccess=async(block,action)=>action==='WRITE'?window.scenario==='full':window.scenario!=='denied';export async function loadCnacDashboard(){window.loadCount=(window.loadCount||0)+1;const actors=Object.fromEntries(actorMetrics.map(d=>[d.sheet,[]]));actors.ATHLETES=[{id_athlete_cnac:'A1',nom_complet:'Athlete',id_sexe:'SEX001',date_de_naissance:'2000-01-01',telephone:'123',email:'a@example.invalid',statut:'ACTIF',id_club_cnac:'C1'}];actors.AUTRES=[{id_autre_acteur_cnac:'O1',id_sexe:'SEX002',statut:'INACTIF'}];const territorial=Object.fromEntries(territorialMetrics.map(d=>[d.sheet,[]]));territorial.ZONES=[{id_zone_cnac:'Z1',nom_zone:'Zone',statut:'ACTIF'}];territorial.CLUBS=[{id_club_cnac:'C1',nom_club:'Club',statut:'ACTIF'}];territorial.EQUIPES=[{id_equipe_cnac:'E1',nom_equipe:'Equipe',statut:'ACTIF'}];const sources={referential:{FEDERATIONS:[{id_federation:'F1',statut:'ACTIF'}],SEXES:[{id_sexe:'SEX001',nom_sexe:'Masculin'},{id_sexe:'SEX002',nom_sexe:'Féminin'}]},territorial,actors,affiliations:{AFFILIATIONS_COACHS:[{id_affiliation_coach:'AF1',id_coach_cnac:'CO1',id_club_cnac:'C1',statut:'ACTIF'},{id_affiliation_coach:'AF2',id_coach_cnac:'CO1',id_club_cnac:'C2',statut:'INACTIF'}]}};if(window.scenario==='partial')delete sources.territorial;if(window.scenario==='empty'){for(const source of Object.values(sources))for(const name of Object.keys(source))source[name]=[];}return{metrics:aggregateCnacMetrics(sources),unavailable:window.scenario==='partial'?['Structures territoriales']:[]}}`);
 await fs.writeFile(path.join(output,'entry.tsx'),`import React,{useState,useEffect}from'react';import{createRoot}from'react-dom/client';import DashboardPage from'@/app/dashboard/page';import{DashboardShell}from'@/components/dashboard/dashboard-shell';function App(){const[view,setView]=useState(null);window.showDashboard=async(scenario)=>{window.scenario=scenario;setView(await DashboardPage())};useEffect(()=>{window.showDashboard('full')},[]);return <DashboardShell access={{'AUT-SPT:READ':true,'AUT-ADM:READ':true}}>{view}</DashboardShell>}createRoot(document.getElementById('root')).render(<App/>);`);
 await new Promise((resolve,reject)=>{const c=webpack({mode:'development',devtool:false,entry:path.join(output,'entry.tsx'),output:{path:output,filename:'bundle.js'},resolve:{alias:{'next/navigation':path.join(output,'navigation.ts'),'@/lib/dashboard/cnac-dashboard':path.join(output,'data.ts'),'@/lib/auth':path.join(output,'data.ts'),'@':root},extensions:['.tsx','.ts','.js']},module:{rules:[{test:/\.tsx?$/,use:path.join(output,'loader.cjs')}]}});c.run((e,s)=>c.close(()=>e||s.hasErrors()?reject(e||new Error(s.toString({all:false,errors:true}))):resolve()))});
 const cssDir=path.join(root,'.next/static/chunks'),css=(await Promise.all((await fs.readdir(cssDir)).filter(f=>f.endsWith('.css')).map(f=>fs.readFile(path.join(cssDir,f),'utf8')))).join('\n');
 const server=http.createServer(async(req,res)=>{if(req.url==='/bundle.js'){res.setHeader('content-type','text/javascript');res.end(await fs.readFile(path.join(output,'bundle.js')))}else if(req.url==='/style.css'){res.setHeader('content-type','text/css');res.end(css)}else{res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script>window.process={env:{NODE_ENV:"development"},browser:true}</script><script src="/bundle.js"></script></body></html>')}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let refreshRequests=0;
  await page.route('**/api/dashboard/refresh',route=>{refreshRequests++;return route.fulfill({json:{ok:true}})});
  await page.route('**/_next/image?*',route=>route.fulfill({contentType:'image/png',path:path.join(root,'public/images/logo-cnac-temp.png')}));
  await page.goto(`http://127.0.0.1:${server.address().port}`);const summary=page.locator('section[aria-labelledby="section-synthese-generale"]');await summary.waitFor();assert.match(await summary.innerText(),/Acteurs enregistrés\s+2/);assert.match(await summary.innerText(),/Structures territoriales\s+3/);assert.match(await summary.innerText(),/Complétude des acteurs\s+50 %/);assert.match(await summary.innerText(),/Affiliations entraîneur–club\s+2/);
  assert.equal(await page.getByRole('heading',{name:'Compétitions',exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Référentiel des acteurs',exact:true}).count(),1);const actors=page.locator('section[aria-labelledby="section-referentiel-des-acteurs"]');assert.equal(await actors.getByRole('cell',{name:'Autres acteurs',exact:true}).count(),1);
  await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});await page.getByRole('button',{name:'Actualiser',exact:true}).click();await page.getByRole('button',{name:'Actualisé',exact:true}).waitFor();assert.equal(refreshRequests,1);assert.equal(await page.evaluate(()=>window.refreshCount),1);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await actors.locator('[data-slot="table-container"]').evaluate(el=>el.scrollWidth>el.clientWidth));
  await page.evaluate(()=>window.showDashboard('partial'));await page.getByRole('alert').waitFor();assert.match(await summary.innerText(),/Structures territoriales\s+Indisponible/);assert.match(await summary.innerText(),/Acteurs enregistrés\s+2/);assert.equal(await page.getByRole('heading',{name:'Référentiel territorial',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Actualiser',exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Tableau de bord',level:1}).count(),1);await page.screenshot({path:path.join(output,'partial-mobile.png'),fullPage:true});
  await page.evaluate(()=>window.showDashboard('empty'));await page.getByText('Aucune donnée enregistrée.',{exact:true}).waitFor();assert.match(await summary.innerText(),/Acteurs enregistrés\s+0/);assert.equal(await page.getByText('Indisponible',{exact:true}).count(),0);
  const loads=await page.evaluate(()=>window.loadCount);await page.evaluate(()=>window.showDashboard('denied'));await page.getByText('Aucun indicateur disponible avec vos autorisations actuelles.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.loadCount),loads);assert.equal(await summary.count(),0);assert.deepEqual(errors,[]);
 }finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}
});
