const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),http=require('node:http');
const {chromium}=require('@playwright/test');const {webpack}=require('next/dist/compiled/webpack/webpack');
test('coach creation, edit, club affiliation statuses, errors and responsive UI',{timeout:120000},async()=>{
  const root=path.resolve(__dirname,'../..'),output=path.join(root,'.cache/coach-affiliations-ui');await fs.mkdir(output,{recursive:true});
  await fs.writeFile(path.join(output,'loader.cjs'),`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=function(source){return ts.transpileModule(source,{fileName:this.resourcePath,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText}`);
  await fs.writeFile(path.join(output,'navigation.ts'),`export const useRouter=()=>({refresh(){},push(){}});export const usePathname=()=>'/dashboard/acteurs/entraineurs';export const useSearchParams=()=>new URLSearchParams();`);
  await fs.writeFile(path.join(output,'entry.tsx'),`import React,{useState}from'react';import{createRoot}from'react-dom/client';import EntraineursClient from '@/app/dashboard/acteurs/entraineurs/entraineurs-client';import{EntraineurDetailClient}from'@/app/dashboard/acteurs/entraineurs/[id]/entraineur-detail-client';const federations=[{id:'FED1',sigle:'F1',nom:'Fédération 1'},{id:'FED2',sigle:'F2',nom:'Fédération 2'}];const coach={id:'CO1',idFederation:'FED1',idNational:'',idFederal:'',idInternational:'',nomComplet:'Coach créé',sexe:'Masculin',idSexe:'SEX001',dateNaissance:'',lieuNaissance:'',nationalite:'',federation:'Fédération 1',telephone:'',email:'',adresse:'',statut:'actif',avatarUrl:null,urlPasseport:null,numeroPasseport:'',dateDelivrancePasseport:'',dateExpirationPasseport:''};function App(){const[detail,setDetail]=useState(false);window.openCoachDetail=()=>setDetail(true);return detail?<EntraineurDetailClient coach={coach} federations={federations}/>:<EntraineursClient coachs={[]} federations={federations}/>}createRoot(document.getElementById('root')).render(<App/>);`);
  await new Promise((resolve,reject)=>{const compiler=webpack({mode:'development',devtool:false,entry:path.join(output,'entry.tsx'),output:{path:output,filename:'bundle.js'},resolve:{alias:{'@':root,'next/navigation':path.join(output,'navigation.ts')},extensions:['.tsx','.ts','.js']},module:{rules:[{test:/\.tsx?$/,use:path.join(output,'loader.cjs')}]}});compiler.run((error,stats)=>compiler.close(()=>error||stats.hasErrors()?reject(error||new Error(stats.toString({all:false,errors:true}))):resolve()))});
  const cssDir=path.join(root,'.next/static/chunks'),css=(await Promise.all((await fs.readdir(cssDir)).filter(file=>file.endsWith('.css')).map(file=>fs.readFile(path.join(cssDir,file),'utf8')))).join('\n');
  const server=http.createServer(async(req,res)=>{if(req.url==='/bundle.js'){res.setHeader('content-type','text/javascript');res.end(await fs.readFile(path.join(output,'bundle.js')))}else if(req.url==='/style.css'){res.setHeader('content-type','text/css');res.end(css)}else{res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html lang="fr"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script>window.process={env:{NODE_ENV:"development"},browser:true}</script><script src="/bundle.js"></script></body></html>')}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
  try{
    browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];page.on('pageerror',error=>{errors.push(error.message);console.error('Fixture browser:',error.message)});let affiliations=[],canWrite=true,fail=false,lastIdentity;
    const clubs=[{id:'C1',nom:'Club compatible',federationId:'FED1'},{id:'C2',nom:'Deuxième club',federationId:'FED1'},{id:'C3',nom:'Club autre fédération',federationId:'FED2'}];
    const save=rows=>{for(const row of rows){const current=affiliations.find(item=>item.id_club_cnac===row.id_club_cnac);if(current)Object.assign(current,row);else affiliations.push({...row,id_affiliation_coach:'AFC-'+(affiliations.length+1),id_coach_cnac:'CO1',nom_club:clubs.find(club=>club.id===row.id_club_cnac).nom})}};
    await page.route('**/api/**',async route=>{const request=route.request(),url=new URL(request.url());if(url.pathname==='/api/coachs/affiliations'){if(request.method()==='GET')return route.fulfill({json:{affiliations:url.searchParams.has('coachId')?affiliations:[],clubs,sexes:[{id_sexe:'SEX001',nom_sexe:'Masculin'}],canWrite}});if(fail){fail=false;return route.fulfill({status:502,json:{error:'Échec Google simulé'}})}save(request.postDataJSON().affiliations);return route.fulfill({json:{ok:true}})}if(url.pathname==='/api/coachs'){lastIdentity=request.postDataJSON();save(lastIdentity.affiliations);return route.fulfill({json:{ok:true,row:{...lastIdentity.row,id_coach_cnac:'CO1',id_coach_coc:'CO1'}}})}return route.fulfill({json:{rows:[],references:{}}})});
    await page.goto(`http://127.0.0.1:${server.address().port}`);await page.getByRole('button',{name:'Ajouter un coach',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByText('Nom complet *',{exact:true}).locator('..').getByRole('textbox').fill('Coach créé');
    await dialog.getByText('Sexe *',{exact:true}).locator('..').getByRole('combobox').click();await page.getByRole('option',{name:'Masculin',exact:true}).click();await dialog.getByText('Fédération *',{exact:true}).locator('..').getByRole('combobox').click();await page.getByRole('option',{name:'F1 — Fédération 1',exact:true}).click();
    await dialog.getByRole('combobox',{name:'Club à rattacher',exact:true}).click();assert.equal(await page.getByRole('option',{name:'Club autre fédération',exact:true}).count(),0);await page.getByRole('option',{name:'Club compatible',exact:true}).click();await dialog.getByRole('button',{name:'Ajouter le rattachement',exact:true}).click();await dialog.getByLabel('Observations du rattachement 1',{exact:true}).fill('Observation initiale');await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(lastIdentity.affiliations[0].id_club_cnac,'C1');assert.equal(lastIdentity.row.id_club_cnac,undefined);
    await page.evaluate(()=>window.openCoachDetail());await page.getByRole('button',{name:'Modifier',exact:true}).waitFor({state:'visible'});await page.getByRole('button',{name:'Modifier',exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.getByLabel('Observations du rattachement 1',{exact:true}).inputValue(),'Observation initiale');await dialog.getByLabel('Observations du rattachement 1',{exact:true}).fill('Observation modifiée');await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(lastIdentity.affiliations[0].observations,'Observation modifiée');
    await page.getByRole('tab',{name:'Affiliations aux clubs',exact:true}).click();await page.getByText('Club compatible',{exact:true}).filter({visible:true}).waitFor();fail=true;await page.getByRole('button',{name:'Désactiver le rattachement',exact:true}).click();await page.getByRole('alert').getByText('Échec Google simulé',{exact:true}).waitFor();assert.equal(affiliations[0].statut,'ACTIF');await page.getByRole('button',{name:'Désactiver le rattachement',exact:true}).click();await page.getByText('INACTIF',{exact:true}).filter({visible:true}).waitFor();assert.equal(affiliations.length,1);await page.getByRole('button',{name:'Réactiver le rattachement',exact:true}).click();await page.getByRole('button',{name:'Désactiver le rattachement',exact:true}).waitFor();
    assert.equal(await page.getByRole('heading',{name:'Affiliations aux clubs',exact:true}).count(),1);
    await page.getByRole('button',{name:'Ajouter une affiliation',exact:true}).click();dialog=page.getByRole('dialog');
    assert.equal(await dialog.getByRole('heading',{name:'Affiliations aux clubs',exact:true}).count(),0);
    await dialog.getByRole('combobox',{name:'Club *',exact:true}).click();assert.equal(await page.getByRole('option',{name:'Club compatible',exact:true}).count(),0);assert.equal(await page.getByRole('option',{name:'Club autre fédération',exact:true}).count(),0);await page.getByRole('option',{name:'Deuxième club',exact:true}).click();
    await dialog.getByLabel('Observations',{exact:true}).fill('Nouvelle affiliation');
    await page.screenshot({path:path.join(output,'add-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'add-mobile.png'),fullPage:true});assert.equal(await dialog.evaluate(el=>el.scrollWidth>el.clientWidth),false);
    fail=true;await dialog.getByRole('button',{name:'Créer',exact:true}).click();await dialog.getByRole('alert').waitFor();assert.equal(await dialog.getByLabel('Observations',{exact:true}).inputValue(),'Nouvelle affiliation');await dialog.getByRole('button',{name:'Créer',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(affiliations.length,2);
    await page.getByRole('button',{name:'Modifier l’affiliation à Deuxième club',exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.getByRole('combobox').count(),1);await dialog.getByLabel('Observations',{exact:true}).fill('Club 2 modifié');await dialog.getByRole('button',{name:'Enregistrer',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal(affiliations[1].observations,'Club 2 modifié');assert.equal(affiliations.length,2);
    await page.getByRole('button',{name:'Consulter l’affiliation à Deuxième club',exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.getByRole('button',{name:'Enregistrer',exact:true}).count(),0);assert.equal(await dialog.getByLabel('Observations',{exact:true}).isDisabled(),true);await dialog.getByRole('button',{name:'Fermer',exact:true}).click();await page.setViewportSize({width:1280,height:1000});
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);canWrite=false;await page.reload();await page.evaluate(()=>window.openCoachDetail());await page.getByRole('tab',{name:'Affiliations aux clubs',exact:true}).click();await page.getByText('Club compatible',{exact:true}).filter({visible:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Désactiver le rattachement',exact:true}).count(),0);assert.deepEqual(errors,[]);
  }finally{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve))}
});
