// En-têtes lus dans les trois classeurs CNAC; aucune colonne créée.
export const CNAC_HEADERS = {
  "SPORTS": [
    "id_sport",
    "nom_sport",
    "description",
    "sport_olympique",
    "statut"
  ],
  "DISCIPLINES": [
    "id_discipline",
    "id_sport",
    "nom_discipline",
    "observations"
  ],
  "ENTITES": [
    "id_entite",
    "id_categorie_entite",
    "nom_officiel",
    "sigle",
    "adresse_siege",
    "telephone",
    "email",
    "site_web",
    "statut",
    "observations"
  ],
  "FEDERATIONS": [
    "id_federation",
    "id_entite",
    "id_sport",
    "statut_reconnaissance_ministere",
    "date_reconnaissance_nationale",
    "statut_affiliation_coc",
    "date_affiliation_coc",
    "id_entite_continentale",
    "date_affiliation_continentale",
    "id_entite_internationale",
    "date_affiliation_internationale",
    "statut",
    "observations"
  ],
  "PROVINCES": [
    "id_province",
    "nom_province",
    "statut",
    "observations"
  ],
  "VILLES": [
    "id_ville",
    "id_province",
    "nom_ville",
    "statut",
    "observations"
  ],
  "CATEGORIES_ENTITES": [
    "id_categorie_entite",
    "nom_categorie_entite",
    "observations"
  ],
  "TYPES_STRUCTURE": [
    "id_type_structure",
    "nom_type_structure",
    "description",
    "observations"
  ],
  "CATEGORIES_CLUB": [
    "id_categorie_club",
    "id_federation",
    "nom_categorie_club",
    "observations"
  ],
  "SEXES": [
    "id_sexe",
    "nom_sexe",
    "observations"
  ],
  "TYPES_ACTEURS": [
    "id_type_acteur",
    "nom_type_acteur",
    "description",
    "statut",
    "observations"
  ],
  "CATEGORIES_AGE": [
    "id_categorie_age",
    "id_federation",
    "id_sport",
    "id_discipline",
    "nom_categorie_age",
    "age_min",
    "age_max",
    "observations"
  ],
  "SPECIALITES_MEDECIN": [
    "id_specialite_sante",
    "nom_specialite_sante",
    "description",
    "observations"
  ],
  "GRADES_ARBITRE": [
    "id_grade_arbitre",
    "id_federation",
    "id_sport",
    "id_discipline",
    "nom_grade",
    "description",
    "observations"
  ],
  "FONCTIONS_OFFICIEL": [
    "id_fonction_acteur",
    "nom_fonction",
    "observations"
  ],
  "HIERARCHIE": [
    "id_hierarchie",
    "id_federation",
    "id_type_structure",
    "niveau_hierarchique",
    "observations"
  ],
  "ZONES": [
    "id_zone_cnac",
    "id_zone_federation",
    "id_federation",
    "nom_zone",
    "sigle_zone",
    "statut",
    "observations"
  ],
  "LIGUES": [
    "id_ligue_cnac",
    "id_ligue_federation",
    "id_federation",
    "id_province",
    "nom_ligue",
    "sigle_ligue",
    "date_creation",
    "date_reconnaissance",
    "telephone",
    "email",
    "statut",
    "observations",
    "id_structure_parent_cnac"
  ],
  "ENTENTES": [
    "id_entente_cnac",
    "id_entente_federation",
    "id_federation",
    "id_structure_parent_cnac",
    "id_ville",
    "nom_entente",
    "sigle_entente",
    "date_creation",
    "date_reconnaissance",
    "telephone",
    "email",
    "statut",
    "observations"
  ],
  "CERCLES": [
    "id_cercle_cnac",
    "id_cercle_federation",
    "id_federation",
    "id_ville",
    "nom_cercle",
    "sigle_cercle",
    "date_creation",
    "date_reconnaissance",
    "telephone",
    "email",
    "statut",
    "observations",
    "id_structure_parent_cnac"
  ],
  "CLUBS": [
    "id_club_cnac",
    "id_club_federation",
    "id_federation",
    "id_structure_parent_cnac",
    "id_categorie_club",
    "id_province",
    "id_ville",
    "nom_club",
    "sigle_club",
    "date_creation",
    "date_affiliation",
    "telephone",
    "email",
    "statut",
    "observations"
  ],
  "EQUIPES": [
    "id_equipe_cnac",
    "id_equipe_federation",
    "id_federation",
    "id_club_cnac",
    "id_sport",
    "id_discipline",
    "id_categorie_age",
    "id_sexe",
    "nom_equipe",
    "statut",
    "observations"
  ],
  "PERSONNES_CONTACT_ENTITES": [
    "id_contact_entite",
    "id_entite",
    "id_type_acteur",
    "id_acteur_cnac",
    "fonction_contact",
    "est_contact_principal",
    "statut",
    "observations"
  ],
  "ATHLETES": [
    "id_athlete_cnac",
    "id_federation",
    "id_athlete_federation",
    "id_national",
    "id_international",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "telephone",
    "email",
    "adresse",
    "statut",
    "avatar_drive_id",
    "avatar_drive_url",
    "observations",
    "id_club_cnac",
    "id_equipe_cnac"
  ],
  "COACHS": [
    "id_coach_cnac",
    "id_federation",
    "id_coach_federation",
    "id_national",
    "id_international",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "telephone",
    "email",
    "adresse",
    "numero_passeport",
    "date_de_delivrance_passeport",
    "date_expiration_passeport",
    "statut",
    "observations"
  ],
  "OFFICIELS": [
    "id_officiel_cnac",
    "id_entite",
    "id_officiel_entite",
    "id_national",
    "id_international",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "telephone",
    "email",
    "adresse",
    "numero_passeport",
    "date_de_delivrance_passeport",
    "date_expiration_passeport",
    "statut",
    "observations"
  ],
  "MEDECINS": [
    "id_medecin_cnac",
    "id_entite",
    "id_medecin_entite",
    "id_national",
    "id_international",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "id_specialite_sante",
    "telephone",
    "email",
    "adresse",
    "numero_passeport",
    "date_de_delivrance_passeport",
    "date_expiration_passeport",
    "statut",
    "observations"
  ],
  "ARBITRES": [
    "id_arbitre_cnac",
    "id_federation",
    "id_arbitre_federation",
    "id_national",
    "id_international",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "telephone",
    "email",
    "adresse",
    "numero_passeport",
    "date_de_delivrance_passeport",
    "date_expiration_passeport",
    "statut",
    "observations"
  ],
  "AUTRES": [
    "id_autre_acteur_cnac",
    "id_entite",
    "id_autre_acteur_entite",
    "nom_complet",
    "id_sexe",
    "date_de_naissance",
    "lieu_de_naissance",
    "nationalite",
    "type_autre_acteur",
    "telephone",
    "email",
    "adresse",
    "numero_passeport",
    "date_de_delivrance_passeport",
    "date_expiration_passeport",
    "statut",
    "observations"
  ]
} as const
export type CnacSheet = keyof typeof CNAC_HEADERS
export const CNAC_KEYS: Record<CnacSheet,string> = {
  "SPORTS": "id_sport",
  "DISCIPLINES": "id_discipline",
  "ENTITES": "id_entite",
  "FEDERATIONS": "id_federation",
  "PROVINCES": "id_province",
  "VILLES": "id_ville",
  "CATEGORIES_ENTITES": "id_categorie_entite",
  "TYPES_STRUCTURE": "id_type_structure",
  "CATEGORIES_CLUB": "id_categorie_club",
  "SEXES": "id_sexe",
  "TYPES_ACTEURS": "id_type_acteur",
  "CATEGORIES_AGE": "id_categorie_age",
  "SPECIALITES_MEDECIN": "id_specialite_sante",
  "GRADES_ARBITRE": "id_grade_arbitre",
  "FONCTIONS_OFFICIEL": "id_fonction_acteur",
  "HIERARCHIE": "id_hierarchie",
  "ZONES": "id_zone_cnac",
  "LIGUES": "id_ligue_cnac",
  "ENTENTES": "id_entente_cnac",
  "CERCLES": "id_cercle_cnac",
  "CLUBS": "id_club_cnac",
  "EQUIPES": "id_equipe_cnac",
  "PERSONNES_CONTACT_ENTITES": "id_contact_entite",
  "ATHLETES": "id_athlete_cnac",
  "COACHS": "id_coach_cnac",
  "OFFICIELS": "id_officiel_cnac",
  "MEDECINS": "id_medecin_cnac",
  "ARBITRES": "id_arbitre_cnac",
  "AUTRES": "id_autre_acteur_cnac"
}
export const CNAC_GROUPS = {
  "REFERENTIEL": [
    "SPORTS",
    "DISCIPLINES",
    "ENTITES",
    "FEDERATIONS",
    "PROVINCES",
    "VILLES",
    "CATEGORIES_ENTITES",
    "TYPES_STRUCTURE",
    "SEXES",
    "TYPES_ACTEURS",
    "CATEGORIES_AGE",
    "SPECIALITES_MEDECIN",
    "GRADES_ARBITRE",
    "FONCTIONS_OFFICIEL"
  ],
  "STRUCTURE_TERRITORIALE": [
    "HIERARCHIE",
    "ZONES",
    "LIGUES",
    "ENTENTES",
    "CERCLES",
    "CLUBS",
    "EQUIPES",
    "PERSONNES_CONTACT_ENTITES"
  ],
  "ACTEURS": [
    "ATHLETES",
    "COACHS",
    "OFFICIELS",
    "MEDECINS",
    "ARBITRES",
    "AUTRES"
  ]
} as const
