export const TERRITORIAL_RESOURCE_BINDINGS = [
  { typeId: "TYPSTR003", key: "zones", sheet: "ZONES", dataKey: "zones", idColumn: "id_zone_cnac", rowIdColumn: "id_zone_coc", federationColumn: "id_federation", federalIdColumn: "id_zone_federation", nameColumn: "nom_zone", aliasColumn: "sigle_zone", parentColumn: "", parentRowColumn: "", parentFallbackColumn: "", parentInputColumn: "", phoneColumn: "", emailColumn: "", statusColumn: "statut" },
  { typeId: "TYPSTR002", key: "ligues", sheet: "LIGUES", dataKey: "ligues", idColumn: "id_ligue_cnac", rowIdColumn: "id_ligue_coc", federationColumn: "id_federation", federalIdColumn: "id_ligue_federation", nameColumn: "nom_ligue", aliasColumn: "pseudo_ligue", parentColumn: "id_structure_parent_cnac", parentRowColumn: "directParentId", parentFallbackColumn: "", parentInputColumn: "id_structure_parent_coc", phoneColumn: "telephone_ligue", emailColumn: "email_ligue", statusColumn: "statut" },
  { typeId: "TYPSTR004", key: "ententes", sheet: "ENTENTES", dataKey: "ententes", idColumn: "id_entente_cnac", rowIdColumn: "id_entente_coc", federationColumn: "id_federation", federalIdColumn: "id_entente_federation", nameColumn: "nom_entente", aliasColumn: "pseudo_entente", parentColumn: "id_structure_parent_cnac", parentRowColumn: "directParentId", parentFallbackColumn: "id_ligue_coc", parentInputColumn: "id_structure_parent_coc", phoneColumn: "telephone_entente", emailColumn: "email_entente", statusColumn: "statut" },
  { typeId: "TYPSTR005", key: "cercles", sheet: "CERCLES", dataKey: "cercles", idColumn: "id_cercle_cnac", rowIdColumn: "id_cercle_coc", federationColumn: "id_federation", federalIdColumn: "id_cercle_federation", nameColumn: "nom_cercle", aliasColumn: "sigle_cercle", parentColumn: "id_structure_parent_cnac", parentRowColumn: "directParentId", parentFallbackColumn: "id_structure_parent_coc", parentInputColumn: "id_structure_parent_coc", phoneColumn: "telephone_cercle", emailColumn: "email_cercle", statusColumn: "statut" },
  { typeId: "TYPSTR006", key: "clubs", sheet: "CLUBS", dataKey: "clubs", idColumn: "id_club_cnac", rowIdColumn: "id_club_coc", federationColumn: "id_federation", federalIdColumn: "id_club_federation", nameColumn: "nom_club", aliasColumn: "sigle_club", parentColumn: "id_structure_parent_cnac", parentRowColumn: "directParentId", parentFallbackColumn: "id_entente_coc", parentInputColumn: "id_structure_parent_coc", phoneColumn: "telephone_club", emailColumn: "email_club", statusColumn: "statut" },
  { typeId: "TYPSTR007", key: "equipes", sheet: "EQUIPES", dataKey: "equipes", idColumn: "id_equipe_cnac", rowIdColumn: "id_equipe_coc", federationColumn: "id_federation", federalIdColumn: "id_equipe_federation", nameColumn: "nom_equipe", aliasColumn: "", parentColumn: "id_club_cnac", parentRowColumn: "directParentId", parentFallbackColumn: "id_club_coc", parentInputColumn: "id_club_coc", phoneColumn: "", emailColumn: "", statusColumn: "statut" },
] as const

export type TerritorialResourceBinding = (typeof TERRITORIAL_RESOURCE_BINDINGS)[number]
export type TerritorialResourceKey = TerritorialResourceBinding["key"]

export function territorialBindingForType(typeId: string) {
  return TERRITORIAL_RESOURCE_BINDINGS.find((binding) => binding.typeId === typeId)
}